# Generated by Django 5.2.4 on 2026-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g., backend_developer', max_length=100)),
                ('tagline', models.CharField(help_text='e.g., scalable systems', max_length=200)),
                ('description', models.TextField(help_text='Main bio description')),
                ('availability_status', models.CharField(default='Available for new opportunities', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('availability_message', models.CharField(default='Open for freelance & full-time roles', max_length=200)),
                ('bio_paragraph_1', models.TextField(blank=True)),
                ('bio_paragraph_2', models.TextField(blank=True)),
                ('bio_paragraph_3', models.TextField(blank=True)),
                ('whoami', models.CharField(default='backend_developer | system_architect', max_length=200)),
                ('interests', models.CharField(default='distributed_systems, performance, open_source', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech', models.JSONField(help_text='Array of technology names')),
                ('metrics', models.JSONField(help_text='Array of metric strings')),
                ('icon', models.CharField(choices=[('Zap', 'Zap'), ('Database', 'Database'), ('Lock', 'Lock'), ('Server', 'Server'), ('Code', 'Code'), ('Globe', 'Globe')], max_length=50)),
                ('github_url', models.URLField(blank=True, default='#')),
                ('demo_url', models.URLField(blank=True, default='#')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('email', 'Email')], max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., 7+, 99.9%, 10M+', max_length=50)),
                ('label', models.CharField(help_text='e.g., Years Experience', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('Terminal', 'Terminal'), ('Server', 'Server'), ('Database', 'Database'), ('Cloud', 'Cloud'), ('Cog', 'Cog'), ('Shield', 'Shield')], max_length=50)),
                ('items', models.JSONField(help_text='Array of technology names')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tech Category',
                'verbose_name_plural': 'Tech Categories',
                'ordering': ['order'],
            },
        ),
    ]
