# Generated by Django 4.2.13 on 2026-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., Jan 2023 – Present', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Brief role description')),
                ('highlights', models.JSONField(default=list, help_text="Key achievements e.g. ['Built billing engine', 'Led team of 3']")),
                ('tech_used', models.JSONField(default=list, help_text='Technologies used in this role')),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_summary',
            field=models.TextField(blank=True, help_text='One-paragraph architecture description'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome_metrics',
            field=models.JSONField(default=list, help_text="Structured results: [{'label': 'Uptime', 'value': '99.9%'}, ...]"),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='What specific problem did this solve? (1–2 sentences)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_highlights',
            field=models.JSONField(default=list, help_text="Key engineering decisions e.g. ['Chose PostgreSQL for JSONB support', 'Used Celery for async billing']"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(help_text='Main bio description (1–2 sentences)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(help_text='Short hook: e.g., I build systems that stay up', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Problem/solution overview (2–3 sentences)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metrics',
            field=models.JSONField(help_text="Array of result strings e.g. ['99.9% uptime', '3x faster']"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text='e.g., 5+, 99.9%, 12+', max_length=50),
        ),
    ]
